return {
	{
		"williamboman/mason.nvim",
		opts = {
			ensure_installed = {
				"ansible-language-server",
				"bash-language-server",
				-- "vim-language-server",
				-- lint and format
				"autopep8",
				"autoflake",
				"black",
				"codespell",
				"djlint",
				"prettierd",
				"jq",
				"mdformat",
				"markuplint",
				"shfmt",
				"shellcheck",
				"shellharden",
				"sqlfmt",
				"yamlfix",
				"yamlfmt",
				"yamllint",
				"yq",
			},
			formaters_by_ft = {
				python = { "black", "autopep8" },
				json = { "jq" },
				markdown = { "mdformat" },
				yaml = { "yamlfmt" },
				sh = { "shfmt" },
				sql = { "sqlfmt" },
				html = { "prettierd" },
				javascript = { "prettierd" },
				typescript = { "prettierd" },
				css = { "prettierd" },
				scss = { "prettierd" },
				less = { "prettierd" },
				graphql = { "prettierd" },
				vue = { "prettierd" },
				svelte = { "prettierd" },
				yaml = { "yamllint", "yamlfmt" },
				json = { "jq" },
			},
			linters_by_ft = {
				python = { "djlint", "flake8", "mypy", "pylint" },
				json = { "jsonlint" },
				markdown = { "markdownlint" },
				yaml = { "yamllint" },
				sh = { "shellcheck", "shellharden" },
				sql = { "sqlfluff" },
				html = { "htmlhint" },
				javascript = { "eslint" },
				typescript = { "eslint" },
				css = { "stylelint" },
				scss = { "stylelint" },
				less = { "stylelint" },
				graphql = { "eslint" },
				vue = { "eslint" },
				svelte = { "eslint" },
				yaml = { "yamllint" },
				json = { "jsonlint" },
				o,
			},
			formaters = {
				shfmt = {
					args = { "-i", "2", "-ci", "-sr" },
				},
			},
		},
	},
}
