return {
	{
		"nvim-treesitter/nvim-treesitter",
		opts = {
			ensure_installed = {
				"bash",
				"c",
				"diff",
				"html",
				"javascript",
				"jsdoc",
				"json",
				"jsonc",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"markdown_inline",
				"python",
				"query",
				"regex",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"yaml",
				-- NonStandard with lazyvim
				"bass",
				"cooklang",
				"dockerfile",
				"hcl",
				"jq",
				"norg",
				"passwd",
				"pem",
				"puppet",
				"sql",
				"ssh_config",
				"strace",
				-- git stuff
				"git_config",
				"git_rebase",
				"gitcommit",
				"gitignore",
				-- Because I deal with these documents I need these
				"todotxt",
				"tsv",
				"psv",
				"csv",
				"xml",
			},
		},
	},
}
