---
# .SYNOPSIS
# Uses go-task to setup a system 
# .INSTALL
# dnf install go-task
# brew install go-task
# .USAGE
# Listing tasks: go-task -l
# Default Install: go-task
# MacOS uses task rather than go-task
# .HELP
# see https://taskfile.dev/
version: "3"
vars:
tasks:
  default:
    desc: Bootstrap system
    cmds:
      - sudo dnf makecache -y
      - sudo dnf install -y go-task vim zsh python-pip python-pip-wheel podman podman-tui
      - sudo dnf install -y cockpit cockpit-selinux restic 
      - sudo dnf install -y mkfontscale cpan restic 
      - sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      - sudo dnf groupupdate core -y
  update_system:
    desc: Update System & Reboot
    cmds:
      - sudo dnf offline-distrosync download -y
      - sudo dnf offline-distrosync reboot -y
