---
# .SYNOPSIS
# Uses go-task to setup a system
# .INSTALL
# dnf install go-task
# brew install go-task
# .USAGE
# Listing tasks: go-task -l
# Default Install: go-task
# MacOS uses task rather than go-task
# .HELP
# see https://taskfile.dev/
version: "3"
vars:
tasks:
  default:
    desc: Choose Wisely?
    deps: []
  simple:
    desc: Installs Starship, SpaceVIM, Fonts, and GRML ZSH - It could be your daily driver if you wanted it to be
    deps: [fonts, grml, spacevim, starship]
  fedora:
    desc: Bootstrap Fedora system
    deps: [terra_repo, rpm_fusion]
    cmds:
      - sudo dnf makecache -y
      - sudo dnf install -y go-task restic python-pip python-pip-wheel 
      - sudo dnf install -y cockpit cockpit-selinux podman podman-tui sqlite 
      - sudo dnf install -y mkfontscale cpan global cargo util-linux-user pcp-system-tools
      - sudo dnf install -y vim zsh tmux powerline tmux-powerline vim-powerline
      - pip install --user -U pip wheel
  fedora_update:
    desc: Update System & Reboot
    cmds:
      - sudo dnf offline-distrosync download -y
      - sudo dnf offline-distrosync reboot -y
  terra_repo:
    desc: Installs the Terra Repo
    cmds:
      - sudo dnf config-manager -y --add-repo https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
  rpm_fusion:
    desc: Installs the RPM Fusion Repo
    cmds:
      - sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      - sudo dnf groupupdate core -y
  fresh:
    env:
      FRESH_LOCAL_SOURCE: hsmalley/dotfiles
    cmds:
      - FRESH_LOCAL_SOURCE=hsmalley/dotfiles bash <(curl -sL https://get.freshshell.com)
  fonts:
    desc: Install Nerd Fonts - FiraCode for IDE, IBM Plex for everything else. Backup fonts are JetBrainsMono & Source Code Pro
    cmds:
      - mkdir -p ~/.local/share/fonts; git clone --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts.git ~/.local/share/fonts/nerd-fonts
      - cd ~/.local/share/fonts/nerd-fonts; git sparse-checkout add patched-fonts/JetBrainsMono
      - cd ~/.local/share/fonts/nerd-fonts; git sparse-checkout add patched-fonts/IBMPlexMono
      - cd ~/.local/share/fonts/nerd-fonts; git sparse-checkout add patched-fonts/SourceCodePro
      - cd ~/.local/share/fonts/nerd-fonts; git sparse-checkout add patched-fonts/FiraCode
      - fc-cache
    status:
      - test -d ~/.local/share/fonts/nerd-fonts
  spacevim:
    desc: Install SpaceVIM - https://spacevim.org/
    deps: [fonts]
    cmds:
      - curl -sLf https://spacevim.org/install.sh | bash
  starship:
    desc: Install Starship.rs - https://starship.rs/
    deps: [fonts]
    cmds:
      - curl -sS https://starship.rs/install.sh | sh
      - echo 'eval "$(starship init zsh)"' | tee -a ~/.zshrc
      - starship preset nerd-font-symbols -o ~/.config/starship.toml
    status:
      - test -f $(which starship)
  oh-my-tmux:
    desc: Installs Oh My Tmux
    dir: ~
    cmds:
      - git clone https://github.com/gpakosz/.tmux.git ~/.tmux
      - ln -s ~/.tmux/.tmux.conf ~/.tmux.conf
  rust_tools:
    desc: Install some rust tools
    cmds:
      - cargo install topgrade bat bottom broot tokei difftastic
  grml:
    desc: Installs GRML ZSH - https://grml.org/zsh/
    cmds:
      - wget -O ~/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
      - wget -O ~/.zshrc.local  https://git.grml.org/f/grml-etc-core/etc/skel/.zshrc
    status:
      - test -f ~/.zshrc
  p10k:
    desc: Make sure you configure Powerlevel 10k after you run zsh to install everything
    cmds:
      - p10k configure
  macos_fonts:
    desc: Install Nerd Fonts for MacOS
    deps: [fonts]
    cmds:
      - find ~/.config/fonts -type f -name "*.ttf" -exec cp {} ~/Library/Fonts/ \;
  macos:
    desc: Sets what I like on MacOS (Reboot Required)
    cmds:
      - defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
      - defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
      - defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
      - defaults write com.apple.screencapture location -string "${HOME}/Downloads"
      - defaults write com.apple.screencapture type -string "png"
      - defaults write com.apple.finder NewWindowTarget -string "PfDe"
      - defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"
      - defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
      - defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
      - defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
      - defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
      - defaults write NSGlobalDomain AppleShowAllExtensions -bool true
      - defaults write com.apple.finder ShowStatusBar -bool true
      - defaults write com.apple.finder QLEnableTextSelection -bool true
      - defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
      - defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
      - defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
      - defaults write NSGlobalDomain com.apple.springing.enabled -bool true
      - defaults write NSGlobalDomain com.apple.springing.delay -float 0.1
      - defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
      - /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
      - /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
      - /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
      - /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist
      - /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist
      - /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist
      - defaults write com.apple.finder FXPreferredViewStyle -string "clmv"
      - chflags nohidden ~/Library
      - defaults write com.apple.dock tilesize -int 60
      - defaults write com.apple.dock expose-animation-duration -float 0.15
      - defaults write com.apple.dock showhidden -bool true
      - defaults write com.apple.universalaccess reduceTransparency -bool true
      - defaults write com.apple.dock wvous-br-corner -int 0
      - defaults write com.apple.dock wvous-br-modifier -int 0
      - defaults write com.apple.dock wvous-tr-corner -int 13
      - defaults write com.apple.dock wvous-tr-modifier -int 0
      - defaults write com.apple.dock wvous-br-corner -int 14
      - defaults write com.apple.dock wvous-br-modifier -int 0
      - defaults write com.apple.dock wvous-bl-corner -int 4
      - defaults write com.apple.dock wvous-bl-modifier -int 0
      - defaults write com.apple.Safari IncludeDevelopMenu -bool true
      - defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
      - defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
      - defaults write NSGlobalDomain WebKitDeveloperExtras -bool true
      - defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false
      - defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
      - defaults write com.apple.ActivityMonitor ShowCategory -int 0
